version: '3.8'

services:
  web:
    image: registry.diikstra.fr/portfolio-v2:latest
    container_name: portfolio-v2
    ports:
      - "8090:8080"
    environment:
      - ENV=prod
      - PORT=8080
    restart: unless-stopped
  