version: "3.1"

services:
  portfolio:
    container_name: portfolio
    image: registry.diikstra.fr/portfolio:${IMAGE_TAG}
    restart: always
    ports:
      - "8090:8080"

networks:
  default:
    name: docker_default